"""
Wine wrapper script generation for winetricks.
Creates wrapper scripts similar to protontricks to properly set up
LD_LIBRARY_PATH and other environment variables before invoking wine/wineserver.
"""

import os
import stat
import shutil
import logging
from pathlib import Path
from typing import Optional

from jackify.shared.paths import get_jackify_data_dir

logger = logging.getLogger(__name__)

WINE_WRAPPER_TEMPLATE = r'''#!/bin/sh
# Wine wrapper script generated by Jackify
# Ensures proper LD_LIBRARY_PATH setup when calling Proton wine binaries

PROTON_DIST_PATH="@@PROTON_DIST_PATH@@"
BINARY_NAME="@@BINARY_NAME@@"
STEAM_RUN_BIN="/run/current-system/sw/bin/steam-run"

# Some Proton console helpers do not emit pipe-capturable stdout under steam-run.
# Emulate the small probe surface that winetricks uses during early startup.
_jackify_resolve_dosdevice() {
    _jackify_drive="$(printf '%s' "$1" | tr 'A-Z' 'a-z')"
    _jackify_link="${WINEPREFIX}/dosdevices/${_jackify_drive}:"
    if command -v readlink >/dev/null 2>&1; then
        _jackify_target="$(readlink -f "${_jackify_link}" 2>/dev/null)"
    else
        _jackify_target=""
    fi
    if [ -n "${_jackify_target}" ]; then
        printf '%s\n' "${_jackify_target}"
    else
        printf '%s\n' "${_jackify_link}"
    fi
}

_jackify_windows_user() {
    _jackify_users_dir="${WINEPREFIX}/drive_c/users"
    for _jackify_candidate in steamuser "${USER:-}" "$(basename "${HOME:-}")"; do
        if [ -n "${_jackify_candidate}" ] && [ -d "${_jackify_users_dir}/${_jackify_candidate}" ]; then
            printf '%s\n' "${_jackify_candidate}"
            return 0
        fi
    done

    if [ -d "${_jackify_users_dir}" ]; then
        for _jackify_dir in "${_jackify_users_dir}"/*; do
            [ -d "${_jackify_dir}" ] || continue
            _jackify_name="$(basename "${_jackify_dir}")"
            case "${_jackify_name}" in
                Public|Default|Default\ User|All\ Users) continue ;;
            esac
            printf '%s\n' "${_jackify_name}"
            return 0
        done
    fi

    printf '%s\n' "steamuser"
}

_jackify_print_windows_env() {
    case "$1" in
        PATH)
            printf '%s\n' 'C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32\WindowsPowerShell\v1.0'
            ;;
        ProgramFiles|ProgramW6432)
            printf '%s\n' 'C:\Program Files'
            ;;
        CommonProgramFiles|CommonProgramW6432)
            printf '%s\n' 'C:\Program Files\Common Files'
            ;;
        'CommonProgramFiles(x86)')
            printf '%s\n' 'C:\Program Files (x86)\Common Files'
            ;;
        AppData)
            _jackify_user="$(_jackify_windows_user)"
            printf '%s\n' "C:\\users\\${_jackify_user}\\AppData\\Roaming"
            ;;
        *)
            return 1
            ;;
    esac
    return 0
}

_jackify_winepath_to_unix() {
    _jackify_input="$1"
    case "${_jackify_input}" in
        [A-Za-z]:/*|[A-Za-z]:\\*)
            _jackify_drive="$(printf '%s' "${_jackify_input}" | cut -c1)"
            _jackify_rest="${_jackify_input#??}"
            _jackify_rest="${_jackify_rest#\\}"
            _jackify_rest="${_jackify_rest#/}"
            _jackify_rest="$(printf '%s' "${_jackify_rest}" | sed 's,\\\\,/,g')"
            _jackify_root="$(_jackify_resolve_dosdevice "${_jackify_drive}")"
            if [ "${_jackify_root}" = "/" ]; then
                if [ -n "${_jackify_rest}" ]; then
                    printf '/%s\n' "${_jackify_rest}"
                else
                    printf '/\n'
                fi
            elif [ -n "${_jackify_rest}" ]; then
                printf '%s/%s\n' "${_jackify_root%/}" "${_jackify_rest}"
            else
                printf '%s\n' "${_jackify_root}"
            fi
            return 0
            ;;
    esac

    printf '%s\n' "${_jackify_input}"
    return 0
}

_jackify_winepath_to_windows() {
    _jackify_input="$1"
    _jackify_best_drive="z"
    _jackify_best_root="/"
    _jackify_best_len=1

    if [ -d "${WINEPREFIX}/dosdevices" ]; then
        for _jackify_link in "${WINEPREFIX}/dosdevices/"*:; do
            [ -e "${_jackify_link}" ] || continue
            if command -v readlink >/dev/null 2>&1; then
                _jackify_root="$(readlink -f "${_jackify_link}" 2>/dev/null)"
            else
                _jackify_root=""
            fi
            [ -n "${_jackify_root}" ] || continue

            case "${_jackify_input}/" in
                "${_jackify_root%/}/"*|"${_jackify_root%/}/")
                    _jackify_len=${#_jackify_root}
                    if [ "${_jackify_len}" -ge "${_jackify_best_len}" ]; then
                        _jackify_best_len=${_jackify_len}
                        _jackify_best_root="${_jackify_root}"
                        _jackify_best_drive="$(basename "${_jackify_link}")"
                        _jackify_best_drive="${_jackify_best_drive%:}"
                    fi
                    ;;
            esac
        done
    fi

    if [ "${_jackify_best_root}" = "/" ]; then
        _jackify_rel="${_jackify_input#/}"
    else
        _jackify_rel="${_jackify_input#"${_jackify_best_root%/}"}"
        _jackify_rel="${_jackify_rel#/}"
    fi

    _jackify_rel="$(printf '%s' "${_jackify_rel}" | sed 's,/,\\\\,g')"
    _jackify_drive="$(printf '%s' "${_jackify_best_drive}" | tr 'a-z' 'A-Z')"
    if [ -n "${_jackify_rel}" ]; then
        printf '%s\n' "${_jackify_drive}:\\${_jackify_rel}"
    else
        printf '%s\n' "${_jackify_drive}:\\"
    fi
    return 0
}

_jackify_maybe_handle_winetricks_probe() {
    if [ -z "${WINEPREFIX:-}" ]; then
        return 1
    fi

    case "$1" in
        cmd|cmd.exe|CMD|CMD.EXE)
            if [ "$2" != "/c" ]; then
                return 1
            fi
            shift 2
            _jackify_cmd="$*"
            case "${_jackify_cmd}" in
                'chcp 65001 > nul & echo %'*'%')
                    _jackify_var="${_jackify_cmd#*echo %}"
                    _jackify_var="${_jackify_var%%%}"
                    _jackify_print_windows_env "${_jackify_var}"
                    return $?
                    ;;
                'echo %'*'%')
                    _jackify_var="${_jackify_cmd#echo %}"
                    _jackify_var="${_jackify_var%%%}"
                    _jackify_print_windows_env "${_jackify_var}"
                    return $?
                    ;;
            esac
            ;;
        winepath)
            case "$2" in
                -u)
                    [ -n "$3" ] || return 1
                    _jackify_winepath_to_unix "$3"
                    return 0
                    ;;
                -w)
                    [ -n "$3" ] || return 1
                    _jackify_winepath_to_windows "$3"
                    return 0
                    ;;
            esac
            ;;
    esac

    return 1
}

# Set up LD_LIBRARY_PATH with Proton libraries first
PROTON_LIB_PATH="${PROTON_DIST_PATH}/lib64:${PROTON_DIST_PATH}/lib"
if [ -n "${LD_LIBRARY_PATH:-}" ]; then
    export LD_LIBRARY_PATH="${PROTON_LIB_PATH}:${LD_LIBRARY_PATH}"
else
    export LD_LIBRARY_PATH="${PROTON_LIB_PATH}"
fi

# Make winetricks probe commands produce deterministic stdout under steam-run.
if [ "${BINARY_NAME}" = "wine" ] || [ "${BINARY_NAME}" = "wine64" ]; then
    if _jackify_maybe_handle_winetricks_probe "$@"; then
        exit 0
    fi
fi

# NixOS needs Proton binaries to run inside steam-run's FHS environment.
if [ -x "${STEAM_RUN_BIN}" ]; then
    exec "${STEAM_RUN_BIN}" "${PROTON_DIST_PATH}/bin/${BINARY_NAME}" "$@"
fi

# Execute the actual Proton binary directly on non-NixOS systems.
exec "${PROTON_DIST_PATH}/bin/${BINARY_NAME}" "$@"
'''


class WineWrapperManager:
    """Manages creation of wine/wineserver wrapper scripts for winetricks."""

    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self._wrapper_dir: Optional[Path] = None

    def get_wrapper_dir(self, proton_path: str) -> Path:
        """Get or create the wrapper directory for a specific Proton version."""
        proton_name = Path(proton_path).name.replace(" ", "_")
        cache_dir = get_jackify_data_dir() / "wine_wrappers" / proton_name
        cache_dir.mkdir(parents=True, exist_ok=True)
        return cache_dir

    def create_wrappers(self, proton_dist_path: str) -> Optional[Path]:
        """
        Create wine and wineserver wrapper scripts for the given Proton dist path.

        Args:
            proton_dist_path: Path to Proton's dist directory (containing bin/, lib/, lib64/)

        Returns:
            Path to the wrapper directory, or None if creation failed
        """
        try:
            proton_dist = Path(proton_dist_path)
            if not proton_dist.exists():
                self.logger.error(f"Proton dist path does not exist: {proton_dist_path}")
                return None

            # Verify required binaries exist
            wine_bin = proton_dist / "bin" / "wine"
            wineserver_bin = proton_dist / "bin" / "wineserver"

            if not wine_bin.exists():
                self.logger.error(f"Wine binary not found: {wine_bin}")
                return None
            if not wineserver_bin.exists():
                self.logger.error(f"Wineserver binary not found: {wineserver_bin}")
                return None

            # Get wrapper directory based on Proton install path (parent of dist)
            proton_install_path = proton_dist.parent
            wrapper_dir = self.get_wrapper_dir(str(proton_install_path))

            # Clean and recreate to ensure fresh scripts
            if wrapper_dir.exists():
                shutil.rmtree(str(wrapper_dir))
            wrapper_dir.mkdir(parents=True, exist_ok=True)

            # Create wrapper for each binary in Proton's bin directory
            binaries_to_wrap = ["wine", "wine64", "wineserver", "wineboot", "winecfg"]
            created_wrappers = []

            for binary_name in binaries_to_wrap:
                binary_path = proton_dist / "bin" / binary_name
                if not binary_path.exists():
                    continue

                wrapper_path = wrapper_dir / binary_name
                wrapper_content = WINE_WRAPPER_TEMPLATE.replace(
                    "@@PROTON_DIST_PATH@@", str(proton_dist)
                ).replace(
                    "@@BINARY_NAME@@", binary_name
                )

                wrapper_path.write_text(wrapper_content)
                wrapper_path.chmod(wrapper_path.stat().st_mode | stat.S_IEXEC)
                created_wrappers.append(binary_name)

            self.logger.info(f"Created wine wrappers in {wrapper_dir}: {', '.join(created_wrappers)}")
            self._wrapper_dir = wrapper_dir
            return wrapper_dir

        except Exception as e:
            self.logger.error(f"Failed to create wine wrappers: {e}", exc_info=True)
            return None

    def get_wine_wrapper_path(self, proton_dist_path: str) -> Optional[str]:
        """Get path to the wine wrapper script."""
        wrapper_dir = self.create_wrappers(proton_dist_path)
        if wrapper_dir:
            wine_wrapper = wrapper_dir / "wine"
            if wine_wrapper.exists():
                return str(wine_wrapper)
        return None

    def get_wineserver_wrapper_path(self, proton_dist_path: str) -> Optional[str]:
        """Get path to the wineserver wrapper script."""
        wrapper_dir = self.create_wrappers(proton_dist_path)
        if wrapper_dir:
            wineserver_wrapper = wrapper_dir / "wineserver"
            if wineserver_wrapper.exists():
                return str(wineserver_wrapper)
        return None
